#!/usr/bin/env python3
"""
test_attack_gen.py — Unit & Integration Test Suite for Modular Attack Generator.

Verifies:
  1. CLI Argument Parsing and Engine Validation (auto, kali, python)
  2. Binary Discovery & Graceful Fallback Logic
  3. Short-duration execution of all pure-Python attack dispatchers
  4. Labeling Oracle Vectorization Consistency (assign_labels_vectorized)
"""

import os
import sys
import time
import socket
import threading
import subprocess
import pandas as pd
import numpy as np

# Add src/, src/defender, src/traffic_gen to PYTHONPATH
ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, os.path.join(ROOT_DIR, "src"))
sys.path.insert(0, os.path.join(ROOT_DIR, "src", "defender"))
sys.path.insert(0, os.path.join(ROOT_DIR, "src", "traffic_gen"))

import attack_flow
import client


def test_cli_parsing():
    print("[*] Test 1: CLI Argument Parsing...")
    script_path = os.path.join(ROOT_DIR, "src", "traffic_gen", "attack_flow.py")
    
    # Test --help returns exit code 0
    res = subprocess.run([sys.executable, script_path, "--help"], capture_output=True, text=True)
    assert res.returncode == 0, f"--help failed: {res.stderr}"
    assert "--engine" in res.stdout, "--engine flag missing from --help"
    assert "kali" in res.stdout and "python" in res.stdout and "auto" in res.stdout, "Engine choices missing"
    print("  [OK] CLI parsing and choices validated.")


def test_tool_discovery():
    print("[*] Test 2: Binary Discovery & Fallback...")
    # Check find_tool with python binary (guaranteed to exist)
    python_name = "python3" if sys.platform != "win32" else "python"
    loc = attack_flow.find_tool(python_name)
    assert loc is not None, f"Could not find {python_name}"

    # Check non-existent binary returns None without error
    loc_none = attack_flow.find_tool("nonexistent_security_binary_xyz_123")
    assert loc_none is None, "Non-existent tool should return None"
    print("  [OK] Binary discovery logic functioning correctly.")


def test_attack_modes_short_execution():
    print("[*] Test 3: Attack Execution Dry-Runs (Python & Auto fallback engines)...")
    target = "127.0.0.1"
    duration = 1  # 1 second quick test
    
    # Test 3a: Benign
    print("  Testing benign mode...")
    attack_flow.run_benign(target, duration)
    
    # Test 3b: SSH Brute Force (Python engine)
    print("  Testing SSH brute force (engine=python)...")
    attack_flow.run_ssh_brute(target, duration, engine="python")
    
    # Test 3c: SSH Brute Force (engine=auto fallback)
    print("  Testing SSH brute force (engine=auto)...")
    attack_flow.run_ssh_brute(target, duration, engine="auto")

    # Test 3d: Slowloris (Python engine)
    print("  Testing Slowloris (engine=python)...")
    attack_flow.run_slowloris(target, duration, port=80, engine="python")

    # Test 3e: DNS Exfil (Python engine)
    print("  Testing DNS Exfil (engine=python)...")
    attack_flow.run_dns_exfil(target, duration, engine="python")

    # Test 3f: Botnet Beacon (Python engine)
    print("  Testing Botnet Beacon (engine=python)...")
    attack_flow.run_botnet_beacon(target, duration, engine="python")

    print("  [OK] All attack dispatchers executed and terminated cleanly.")


def test_label_oracle_compliance():
    print("[*] Test 4: Threat Labeling Oracle Vectorization Consistency...")
    tg_ip = "10.10.140.10"
    target_ip = "10.10.110.15"

    # Create mock flow records reflecting the traffic generated by the engines
    flows = [
        # Normal (Defender curl)
        {"src_ip": "10.10.130.11", "dst_ip": target_ip, "src_port": 54321, "dst_port": 80, "duration_ms": 50},
        # Botnet C2 (Port 8080)
        {"src_ip": tg_ip, "dst_ip": target_ip, "src_port": 45000, "dst_port": 8080, "duration_ms": 1500},
        # Botnet C2 (Port 9000)
        {"src_ip": tg_ip, "dst_ip": target_ip, "src_port": 45001, "dst_port": 9000, "duration_ms": 800},
        # DNS Exfil (Port 53)
        {"src_ip": tg_ip, "dst_ip": target_ip, "src_port": 50000, "dst_port": 53, "duration_ms": 10},
        # SSH Brute Force (Port 22)
        {"src_ip": tg_ip, "dst_ip": target_ip, "src_port": 50001, "dst_port": 22, "duration_ms": 200},
        # Slowloris DoS (Port 80, long duration > 2000ms)
        {"src_ip": tg_ip, "dst_ip": target_ip, "src_port": 50002, "dst_port": 80, "duration_ms": 4500},
    ]
    df = pd.DataFrame(flows)
    labels = client.assign_labels_vectorized(df, dos_threshold_ms=2000, traffic_gen_ip=tg_ip)

    expected_labels = np.array([0, 1, 1, 2, 3, 4], dtype=np.int64)
    assert np.array_equal(labels, expected_labels), f"Label mismatch! Got {labels}, expected {expected_labels}"
    print(f"  [OK] Vectorized labeling accurately mapped: {labels.tolist()} == {expected_labels.tolist()}")


def main():
    print("=" * 60)
    print("  FL-CL Attack Generation & Engine Verification Suite")
    print("=" * 60)
    
    test_cli_parsing()
    test_tool_discovery()
    test_attack_modes_short_execution()
    test_label_oracle_compliance()
    
    print("\n" + "=" * 60)
    print("  [SUCCESS] All Attack Generation Tests Passed!")
    print("=" * 60)


if __name__ == "__main__":
    main()
