"""
inference_loop.py — Continuous Real-Time Inference Loop for FCL Defender Nodes.

Monitors the flow CSV folder for new batches generated by extractor.py,
runs class inference using the latest master TorchScript model, logs attack alerts,
and automatically hot-reloads the model if updated.

Usage:
    python3 inference_loop.py --checkpoint /opt/mlflow-artifacts/checkpoints/model_latest_scripted.pt --flows-dir /mnt/ramdisk/flows
"""

import argparse
import os
import sys
import time
import json
from pathlib import Path

import numpy as np
import pandas as pd
import torch

LABEL_NAMES = {0: "Normal", 1: "Botnet", 2: "Exfiltration", 3: "BruteForce", 4: "DoS"}
FEATURE_COLS = [
    "bidirectional_packets", "bidirectional_bytes", "duration_ms",
    "src2dst_packets", "src2dst_bytes", "dst2src_packets", "dst2src_bytes",
    "src2dst_mean_piat_ms", "dst2src_mean_piat_ms",
    "dst_port",
]


def load_model(checkpoint_path, device):
    """Load TorchScript model from path."""
    if not os.path.exists(checkpoint_path):
        raise FileNotFoundError(f"Model checkpoint not found at: {checkpoint_path}")
    print(f"[inference] Loading model from: {checkpoint_path}")
    model = torch.jit.load(checkpoint_path, map_location=device)
    model.eval()
    return model, os.path.getmtime(checkpoint_path)


def preprocess_batch(df):
    """Extract, scale, and pad features to match model requirements."""
    available_cols = [c for c in FEATURE_COLS if c in df.columns]
    X = df[available_cols].fillna(0).values.astype(np.float32)

    # Standardize handling single-sample / zero-variance cases
    if X.shape[0] > 0:
        mean = X.mean(axis=0)
        std = X.std(axis=0)
        std[std == 0.0] = 1.0  # Avoid division by zero
        X = (X - mean) / std
    
    # Pad/truncate to 32 dimensions (CyberDefenseNet expected size)
    if X.shape[1] < 32:
        padding = np.zeros((X.shape[0], 32 - X.shape[1]), dtype=np.float32)
        X = np.hstack([X, padding])
    elif X.shape[1] > 32:
        X = X[:, :32]

    return torch.tensor(X)


def process_flow_file(file_path, model, device, threshold, alerts_log):
    """Run model inference on a single flow CSV and log alerts."""
    try:
        df = pd.read_csv(file_path)
    except Exception as e:
        print(f"[inference] Error reading {file_path.name}: {e}")
        return

    if df.empty:
        return

    X = preprocess_batch(df)
    
    with torch.no_grad():
        X = X.to(device)
        outputs = model(X)
        probs = torch.softmax(outputs, dim=1)
        confidences, predictions = torch.max(probs, dim=1)
        
        confidences = confidences.cpu().numpy()
        predictions = predictions.cpu().numpy()

    alerts_triggered = 0
    for idx, (pred_cls, conf) in enumerate(zip(predictions, confidences)):
        if pred_cls > 0 and conf >= threshold:
            row = df.iloc[idx]
            alert = {
                "timestamp": time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()),
                "src_ip": str(row.get("src_ip", "0.0.0.0")),
                "dst_ip": str(row.get("dst_ip", "0.0.0.0")),
                "src_port": int(row.get("src_port", 0)),
                "dst_port": int(row.get("dst_port", 0)),
                "protocol": int(row.get("protocol", 0)),
                "predicted_class": int(pred_cls),
                "predicted_label": LABEL_NAMES[pred_cls],
                "confidence": float(conf)
            }
            
            # Print high-visibility warning to terminal
            print(f"\n[ALERT] Malicious Traffic Detected!")
            print(f"   Type:       {alert['predicted_label']} (Confidence: {alert['confidence']:.2%})")
            print(f"   Connection: {alert['src_ip']}:{alert['src_port']} -> {alert['dst_ip']}:{alert['dst_port']} (Proto: {alert['protocol']})")
            
            # Write alert JSON line to log file
            try:
                with open(alerts_log, "a") as f:
                    f.write(json.dumps(alert) + "\n")
            except Exception as e:
                print(f"[inference] Error writing alert log: {e}")
            
            alerts_triggered += 1
            
    if alerts_triggered > 0:
        print(f"[inference] Processed {file_path.name}: Triggered {alerts_triggered} alerts.")


def main():
    parser = argparse.ArgumentParser(description="Real-Time FCL Inference Loop")
    parser.add_argument("--checkpoint", default="/opt/mlflow-artifacts/checkpoints/model_latest_scripted.pt", help="Path to TorchScript model checkpoint")
    parser.add_argument("--flows-dir", default="/mnt/ramdisk/flows", help="Directory where extractor writes CSVs")
    parser.add_argument("--alert-threshold", type=float, default=0.70, help="Confidence threshold to trigger alerts")
    parser.add_argument("--poll-interval", type=float, default=1.0, help="Polling interval in seconds")
    parser.add_argument("--alerts-log", default="/mnt/ramdisk/flows/alerts.json", help="Output file path for security alerts")
    args = parser.parse_args()

    print("=" * 62)
    print("      FL-CL Cyber Defense - Real-Time Inference Loop")
    print("=" * 62)
    print(f"Model Checkpoint: {args.checkpoint}")
    print(f"Flows Directory:  {args.flows_dir}")
    print(f"Alert Threshold:  {args.alert_threshold:.0%}")
    print(f"Alert Log Path:   {args.alerts_log}")
    print("=" * 62)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    
    # Wait for the model checkpoint to become available
    while not os.path.exists(args.checkpoint):
        print(f"[inference] Waiting for model checkpoint at {args.checkpoint}...")
        time.sleep(5.0)

    model, last_mtime = load_model(args.checkpoint, device)
    
    # Ensure directories exist
    os.makedirs(args.flows_dir, exist_ok=True)
    os.makedirs(os.path.dirname(os.path.abspath(args.alerts_log)), exist_ok=True)

    # Track already processed files to avoid duplicate alert triggers
    processed_files = set(Path(args.flows_dir).glob("flows_*.csv"))
    print(f"[inference] Monitoring started. Initialized with {len(processed_files)} existing files.")

    try:
        while True:
            # 1. Check for model updates (dynamic hot-reloading)
            try:
                current_mtime = os.path.getmtime(args.checkpoint)
                if current_mtime > last_mtime:
                    print(f"\n[inference] Model change detected on disk!")
                    model, last_mtime = load_model(args.checkpoint, device)
            except Exception as e:
                pass  # Ignore temporary locks on model update

            # 2. Check for new flow CSV files
            current_files = set(Path(args.flows_dir).glob("flows_*.csv"))
            new_files = sorted(list(current_files - processed_files))
            
            for file_path in new_files:
                # Wait briefly to ensure writing has completed
                time.sleep(0.1)
                process_flow_file(file_path, model, device, args.alert_threshold, args.alerts_log)
                processed_files.add(file_path)

            time.sleep(args.poll_interval)
            
    except KeyboardInterrupt:
        print("\n[inference] Stopping inference loop. Exiting...")
        sys.exit(0)


if __name__ == "__main__":
    main()
